// src/lib/icons.ts

// ✅ NOVOS ÍCONES DE BANCOS E FINANÇAS ADICIONADOS
const bankAndFinanceIcons = [
  "bank:itau",
  "bank:bradesco",
  "bank:bb",
  "bank:caixa",
  "bank:santander",
  "bank:nubank",
  "bank:inter",
  "bank:c6",
  "bank:btg",
  "bank:banrisul",
  // Cartões
  "logos:mastercard",
  "logos:visa",
  // Geral
  "fa6-brands:pix",
  "fa6-solid:landmark",
  "fa6-solid:money-bill-wave",
  "fa6-solid:wallet",
  "fa6-solid:piggy-bank",
  "fa6-solid:credit-card",
];

const generalIcons = [
  "fa6-solid:house-chimney",
  "fa6-solid:building-user",
  "fa6-solid:file-invoice-dollar",
  "fa6-solid:wifi",
  "fa6-solid:mobile-screen-button",
  "fa6-solid:arrows-rotate",
  "fa6-solid:hand-holding-dollar",
  "fa6-solid:arrow-trend-up",
  "fa6-solid:briefcase-medical",
  "fa6-solid:graduation-cap",
  "fa6-solid:martini-glass-citrus",
  "fa6-solid:utensils",
  "fa6-solid:bus",
  "fa6-solid:bag-shopping",
  "fa6-solid:dumbbell",
  "fa6-solid:paw",
  "fa6-solid:phone",
  "fa6-solid:file-contract",
  "fa6-solid:money-bill-transfer",
  "fa6-solid:box-archive",
  "fa6-solid:car",
  "fa6-solid:gas-pump",
  "fa6-solid:plane",
  "fa6-solid:motorcycle",
  "fa6-solid:train-subway",
  "fa6-solid:cart-shopping",
  "fa6-solid:shirt",
  "fa6-solid:gift",
  "fa6-solid:gamepad",
  "fa6-solid:film",
  "fa6-solid:book",
  "fa6-solid:music",
  "fa6-solid:laptop-code",
  "fa6-solid:computer",
  "fa6-solid:bolt",
  "fa6-solid:lightbulb",
  "fa6-solid:droplet",
  "fa6-solid:fire",
  "fa6-solid:key",
  "fa6-solid:shield-halved",
  "fa6-solid:hammer",
  "fa6-solid:wrench",
  "fa6-solid:star",
  "fa6-solid:heart",
  "fa6-solid:user-doctor",
  "fa6-solid:pills",
  "fa6-solid:stethoscope",
  "fa6-solid:school",
  "fa6-solid:child",
  "fa6-solid:baby-carriage",
  "fa6-solid:dog",
  "fa6-solid:cat",
  "fa6-solid:burger",
  "fa6-solid:pizza-slice",
  "fa6-solid:ice-cream",
  "fa6-solid:beer-mug-empty",
  "fa6-solid:wine-glass",
  "fa6-solid:camera-retro",
  "fa6-solid:paintbrush",
  "fa6-solid:plane-departure",
  "fa6-solid:umbrella-beach",
  "fa6-solid:bed",
  "fa6-solid:bath",
  "fa6-solid:couch",
  "fa6-solid:tv",
  "fa6-solid:dollar-sign",
  "fa6-solid:euro-sign",
  "fa6-solid:brazilian-real-sign",
  "fa6-solid:coins",
  "fa6-solid:tree",
  "fa6-solid:seedling",
  "fa6-solid:bicycle",
  "fa6-solid:futbol",
  "fa6-solid:person-swimming",
];

// ✅ LISTA FINAL COMBINANDO TUDO
export const availableIcons = [...bankAndFinanceIcons, ...generalIcons];
